title: Giulio's Zettelkasten

permalink: pretty

plugins:
  - jekyll-relative-links
  - jekyll-redirect-from

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "**/*.md"
    values:
      layout: "note"

relative_links:
  enabled: true
  collections: true
