title:               My digital garden
include:             ['_pages']

permalink:           pretty

plugins:
  - jekyll-last-modified-at
  - jekyll-relative-links
sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"

relative_links:
  enabled:     true
  collections: true
