title: Giulio's Zettelkasten

permalink: pretty

plugins:
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-pandoc

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "**/*.md"
    values:
      layout: "note"

markdown: Pandoc

pandoc:
  extensions:
    - bibliography: _notes/literature-notes/references.bib

relative_links:
  enabled: true
  collections: true
